name: Build

on:
    - push
    - pull_request
    - workflow_dispatch

jobs:
    build:
        runs-on: ${{ matrix.config.os }}

        strategy:
            matrix:
                config:
                    -   os: ubuntu-latest
                        params: "build integrationTest functionalTest"

                    -   os: windows-latest
                        params: "build integrationTest functionalTest"

                    -   os: macos-latest
                        params: "build integrationTest functionalTest"

        steps:
            -   name: Checkout Source Code
                uses: actions/checkout@v3.6.0

            -   name: Install Java
                uses: actions/setup-java@v3.12.0
                with:
                    distribution: zulu
                    java-version: 17

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2.7.1
                with:
                    cache-read-only: ${{ github.event_name == 'pull_request' }}

            -   name: Build and Unit Test
                run: ./gradlew ${{ matrix.config.params }}
