name: Build

on:
    - pull_request
    - workflow_dispatch

jobs:
    build:
        runs-on: ${{ matrix.config.os }}

        strategy:
            matrix:
                config:
                    -   os: ubuntu-latest
                    -   os: windows-latest
                    -   os: macos-latest
        steps:
            -   name: Checkout Source Code
                uses: actions/checkout@v3.6.0
                with:
                    fetch-depth: '0'

            -   name: Install Java
                uses: actions/setup-java@v3.12.0
                with:
                    distribution: zulu
                    java-version: 17

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2.7.1
                with:
                    cache-read-only: ${{ github.event_name == 'pull_request' }}

            -   name: Build and Unit Testing
                run: ./gradlew build

            -   name: Integration Testing
                run: ./gradlew integrationTest

            -   name: Functional Testing
                run: ./gradlew functionalTest
