name: Publish

on:
    push:
        tags:
            - '*'

jobs:
    linux:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Source Code
                uses: actions/checkout@v3.6.0

            -   name: Fetch Git Tags
                run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

            -   name: Install Java
                uses: actions/setup-java@v3.12.0
                with:
                    distribution: zulu
                    java-version: 17

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2.7.1

            -   name: Build
                run: ./gradlew build integrationTest functionalTest

            -   name: Publish
                run: ./gradlew publishPlugins -Pgradle.publish.key=${{secrets.PUBLISH_KEY}} -Pgradle.publish.secret=${{secrets.PUBLISH_SECRET}}
